feat: always set omitempty on pointer fields
Khan/genqlient pull request #287
Opened 2023-07-27 09:26 UTC by obitech

When optional: "pointer" is configured, omitempty is needed for input fields for the generated code to be semantically correct. Without omitempty an empty pointer would generate an "empty value" which is incorrect.

Consider the following graphql schema generated by Hasura:

input task_insert_input {
  id: Int
}
Without this fix, the following golang struct will be generated:

type Task_insert_input struct {
  Id: *int `json:"id"`
}

* Ref: https://github.com/Khan/genqlient/issues/260
* Ref: https://github.com/Khan/genqlient/pull/264

I have:
- [x] Written a clear PR title and description (above)
- [x] Signed the [Khan Academy CLA](https://www.khanacademy.org/r/cla)
- [ ] Added tests covering my changes, if applicable
- [x] Included a link to the issue fixed, if applicable
- [x] Included documentation, for new features
- [x] Added an entry to the changelog

2023-08-01 03:28 UTC, benjaminjkraft requested changes
Thanks for picking this up!

I think my comment in the original PR that we'll need this flagged somehow is still relevant:

> I think as-is this is in some sense a breaking change, although perhaps anyone who cares about this prefers the new behavior? It also seems confusing to do this only and automatically for `optional: pointer`, which right now is I think otherwise equivalent to `# @genqlient(pointer: true)` on every optional field. Maybe we add a new config `optional: pointer_and_omitempty` and handle both issues that way?
> 
> (Edit: Thinking more, doing a new config doesn't strictly handle the second issue -- you could want this for non-`pointer: true` fields. But I guess you can always annotate those individually, and probably you never want it for non-pointer fields globally (since that means `false` gets omitted). So I guess it's still maybe the best compromise.)

I'm not sure if it makes more sense to do a completely separate option, or a separate value for `optional`, or what, but we'll need one or the other! Eventually maybe we change the default here but I'd like to see more of how `optional: generic` (and generally Go style around how to represent `Optional[T]`) develops, if nothing else, so I think for now it's best to avoid that. (Plus, really, what we need is a Hasura template -- at which point it doesn't matter what the defaults are. A reminder to comment on #272 if you have any thoughts!)

And it still needs some tests and documentation for the new behavior :-) .

2023-10-26 00:06 UTC, justonia commented
What's the status on this? I'm working with the Linear API and it's broken if `omitempty` isn't supported.

2023-12-18 23:26 UTC, staugaard commented
I'm also waiting for this feature.

2024-02-15 04:18 UTC, benjaminjkraft commented
Closing in favor of #308 which uses a config option

2024-02-15 04:18 UTC, closed without merging